#!/bin/bash

[ "$TESTONLINUX" = "" ] && exit 0
source "$TESTONLINUX/lib/sources"

TITLE="Test a whole function"

POLT_CLI_Title "$TITLE"

POLT_System_GetList
i=1
while read script; do
		echo "$i) $script"
		i=$(( i + 1 ))
done < "$POLT_USER_ROOT/scripts"
POLT_CLI_scanf "Your choice?" "num"

choosen_script="$(cat "$POLT_USER_ROOT/scripts" | getline "$num")"

POLT_System_GetTests "$choosen_script"
POLT_System_TestList "$choosen_script" || POL_CLI_fatal "No tests downloaded"
i=1
for test in $(cat "$POLT_USER_ROOT/tests/${choosen_script}_header"); do
	echo "$i) $test"
	i=$(( i + 1 ))
done

success="true"
for (( j = 0; j < i; j ++ ))
{
	choosen_test="$(cat "$POLT_USER_ROOT/tests/${choosen_script}_header" | getline "$num")"
	echo "Testing $j : $choosen_test"
	source "$POLT_USER_ROOT/tests/${choosen_script}"
	if "$choosen_test"; then
		echo "Test succed"
	else
		echo "Test failed."
		success="false"
		break
	fi
}

if [ "$success" = "true" ]; then
	echo "All test are successfull"
else
	echo "Failed"
fi