#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2011 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.   

                              #######                           
                           ############                         
                          ##################                    
                          ########################              
             ######       ##########################            
         #############    ###########################           
        ###############    ##########################           
       #################   ##########################           
      ##################    #########################           
      ###################    #######################            
    ######################   #####################              
   ########################   #################                 
  #########################    ###########        ######        
 ###########################   ######        #############      
 ##############################       ######################    
  ##########################   #############################    
   ##################        ##   ##########################    
     ###########        ########   ########################     
                   ##############   ######################      
              ####################   ####################       
           #######################    ##################        
          #########################    ################         
         ###########################    ###############         
         ###########################     ##############         
         ###########################      ############          
          ##########################         #######            
             ######################                             
                     #############                              
                       #########                                

#Variables
die() ## PHP function copy
{
	echo "$@"
	exit
}

export WorkingDirectory="$PWD"

# Take absolute path this script resides in
TESTONLINUX="$(dirname "$0")"
cd "$TESTONLINUX"
export TESTONLINUX="$PWD"

[ "$(uname -s)" = "Darwin" ] && export POLT_OS="Mac" || export POLT_OS="$(uname -s)"

source "$TESTONLINUX/lib/sources"

# Ok we are now good

POLT_System_BuildRep
POLT_System_GetModuleList

